---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - ansible --version

  # Install docker
  - ansible-galaxy install angstwad.docker_ubuntu
  - ansible-playbook tests/docker.yml --sudo -i tests/inventory

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --sudo -vvvv

notifications:
  slack:
    secure: >-
      ucja5p1keTY7vPuZHRBq8AN2mkhzvSSlqzmhqsDWNBnZ5UI7lQkLjG4iKpiBYCPiLixzSX09l
      aHHH+yVPg5DqKSSn+VGATs1nrobW2qId9ts+WLxmcA9DKaqlqO8SqqzrmC8+50bE2obPs3/AZ
      1eKzlzrnPmX9xj18kwT9MyLw+ZAS+BZ7QI3t3f8WK3+6MoAD7Xef6rtcHIXI7UBn9MgWhXjj/
      EJv+8LTMzeSl2w122ybn18m97aGThqqKdYWaJgVrXXCAwxws4chy9OKHZUxDHnH+emAXP19AJ
      rjLzxIseQwS601yhQPIkiN1iT4xFoAHF5Ur8BNuJxg0xBAhqvkxOe+sarHRTl4lMzQtm3czp6
      kS0s1QBWHmMYttNOPohADQIPwDDuSC+ZuUA/fbQ7Lyts2yEheIY0YGYCXvg2c1Cr2poF5qHZJ
      g5E4VWQF+t0EolHvDBA0WAsXD55//NsA33EeR7O31QYgN9blXaNzrMDE8FMg7lkdxcXecSl3j
      Pn3jffe0YWv7HrXTHywMNKBXaSKsvJW+Il9fKRkeM5XRpMVKwsLoKQFge1C6uOAdmFJdn6HFD
      EbtKQeHXDoMbOtYHr/TSEpubL/j19qF3S3MzuwGJDclpSY24qdlkKA0aae+bnc65gQQC0NwZ2
      DiVGlWHz9nFZyrsfOQEQdJy6ZE=
    on_success: change
    on_failure: always
