---

- name: check/create data store container
  docker_container:
    name: "{{ datastore_container_name }}"
    image: >-
      postgres{{ ':%s' % postgres_docker_tag if postgres_docker_tag else '' }}
    state: present
    volumes:
      - /var/lib/postgresql/data
    command: "true"
  when: use_datastore_container

- name: check/create postgresql container
  docker_container:
    name: "{{ postgres_container_name }}"
    image: >-
      postgres{{ ':%s' % postgres_docker_tag if postgres_docker_tag else '' }}
    state: started
    restart_policy: always
    env: "{{ postgres_docker_env if postgres_docker_env else omit }}"
    volumes_from: >-
      {{ [datastore_container_name] if use_datastore_container else omit }}
    exposed_ports: "{{ ['%s:5432' % expose_host_port] if expose_host_port else omit }}"

- name: inspect postgres docker
  command: >
    docker inspect --type=container
    --format='{{ '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' }}'
    {{ postgres_container_name }}
  register: postgres_address_result

- set_fact: postgres_container_address={{ postgres_address_result.stdout }}
